In [1]:
spark

In [2]:
!hadoop fs -ls /user/msd24002/

Found 7 items
drwxr-xr-x   - msd24002 hadoop          0 2025-04-07 14:39 /user/msd24002/.sparkStaging
-rw-r--r--   2 msd24002 hadoop    1060750 2025-04-13 10:57 /user/msd24002/customers1mb.csv
drwxr-xr-x   - msd24002 hadoop          0 2025-03-30 14:52 /user/msd24002/input
-rw-r--r--   2 msd24002 hadoop        141 2025-04-07 14:04 /user/msd24002/input.txt
drwxr-xr-x   - msd24002 hadoop          0 2025-04-07 14:39 /user/msd24002/output_two_parts
drwxr-xr-x   - msd24002 hadoop          0 2025-03-30 14:54 /user/msd24002/output_two_reducers
drwxr-xr-x   - msd24002 hadoop          0 2025-04-07 14:18 /user/msd24002/output_wordcount

In [3]:
df_2=spark.read \
.format('csv')\
.option('header',"true")\
.load('/data/first_100_customers.csv')

In [4]:
df_2.show()

+-----------+-----------+---------+-----------+-------+-----------------+---------+
|customer_id|       name|     city|      state|country|registration_date|is_active|
+-----------+-----------+---------+-----------+-------+-----------------+---------+
|          0| Customer_0|     Pune|Maharashtra|  India|       2023-06-29|    False|
|          1| Customer_1|Bangalore| Tamil Nadu|  India|       2023-12-07|     True|
|          2| Customer_2|Hyderabad|    Gujarat|  India|       2023-10-27|     True|
|          3| Customer_3|Bangalore|  Karnataka|  India|       2023-10-17|    False|
|          4| Customer_4|Ahmedabad|  Karnataka|  India|       2023-03-14|    False|
|          5| Customer_5|Hyderabad|  Karnataka|  India|       2023-07-28|    False|
|          6| Customer_6|     Pune|      Delhi|  India|       2023-08-29|    False|
|          7| Customer_7|Ahmedabad|West Bengal|  India|       2023-12-28|     True|
|          8| Customer_8|     Pune|  Karnataka|  India|       2023-06-22|     True|
|          9| Customer_9|   Mumbai|  Telangana|  India|       2023-01-05|     True|
|         10|Customer_10|     Pune|    Gujarat|  India|       2023-08-05|     True|
|         11|Customer_11|    Delhi|West Bengal|  India|       2023-08-02|    False|
|         12|Customer_12|  Chennai|    Gujarat|  India|       2023-11-21|    False|
|         13|Customer_13|  Chennai|  Karnataka|  India|       2023-11-06|     True|
|         14|Customer_14|Hyderabad| Tamil Nadu|  India|       2023-02-07|    False|
|         15|Customer_15|   Mumbai|    Gujarat|  India|       2023-03-02|     True|
|         16|Customer_16|  Chennai|  Karnataka|  India|       2023-04-05|    False|
|         17|Customer_17|Hyderabad|West Bengal|  India|       2023-08-21|    False|
|         18|Customer_18|     Pune|      Delhi|  India|       2023-10-04|     True|
|         19|Customer_19|  Kolkata|    Gujarat|  India|       2023-02-05|     True|
+-----------+-----------+---------+-----------+-------+-----------------+---------+
only showing top 20 rows

In [6]:
df_2.printSchema()

root
 |-- customer_id: string (nullable = true)
 |-- name: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- country: string (nullable = true)
 |-- registration_date: string (nullable = true)
 |-- is_active: string (nullable = true)

In [8]:
 active_customers=df_2.filter('is_active=true')

In [9]:
active_customers

DataFrame[customer_id: string, name: string, city: string, state: string, country: string, registration_date: string, is_active: string]

In [10]:
active_customers.show()

+-----------+-----------+---------+-----------+-------+-----------------+---------+
|customer_id|       name|     city|      state|country|registration_date|is_active|
+-----------+-----------+---------+-----------+-------+-----------------+---------+
|          1| Customer_1|Bangalore| Tamil Nadu|  India|       2023-12-07|     True|
|          2| Customer_2|Hyderabad|    Gujarat|  India|       2023-10-27|     True|
|          7| Customer_7|Ahmedabad|West Bengal|  India|       2023-12-28|     True|
|          8| Customer_8|     Pune|  Karnataka|  India|       2023-06-22|     True|
|          9| Customer_9|   Mumbai|  Telangana|  India|       2023-01-05|     True|
|         10|Customer_10|     Pune|    Gujarat|  India|       2023-08-05|     True|
|         13|Customer_13|  Chennai|  Karnataka|  India|       2023-11-06|     True|
|         15|Customer_15|   Mumbai|    Gujarat|  India|       2023-03-02|     True|
|         18|Customer_18|     Pune|      Delhi|  India|       2023-10-04|     True|
|         19|Customer_19|  Kolkata|    Gujarat|  India|       2023-02-05|     True|
|         20|Customer_20|Hyderabad|  Telangana|  India|       2023-01-01|     True|
|         21|Customer_21|Bangalore| Tamil Nadu|  India|       2023-05-30|     True|
|         22|Customer_22|  Chennai|West Bengal|  India|       2023-08-03|     True|
|         26|Customer_26|    Delhi|      Delhi|  India|       2023-03-22|     True|
|         27|Customer_27|Ahmedabad|    Gujarat|  India|       2023-07-08|     True|
|         28|Customer_28|Hyderabad|Maharashtra|  India|       2023-05-31|     True|
|         34|Customer_34|  Kolkata|    Gujarat|  India|       2023-11-01|     True|
|         36|Customer_36|Ahmedabad| Tamil Nadu|  India|       2023-10-07|     True|
|         37|Customer_37|Hyderabad|  Karnataka|  India|       2023-03-21|     True|
|         42|Customer_42|Bangalore|    Gujarat|  India|       2023-08-11|     True|
+-----------+-----------+---------+-----------+-------+-----------------+---------+
only showing top 20 rows

In [12]:
selected_columns=df_2.select('customer_id','name','city')

In [13]:
selected_columns.show()

+-----------+-----------+---------+
|customer_id|       name|     city|
+-----------+-----------+---------+
|          0| Customer_0|     Pune|
|          1| Customer_1|Bangalore|
|          2| Customer_2|Hyderabad|
|          3| Customer_3|Bangalore|
|          4| Customer_4|Ahmedabad|
|          5| Customer_5|Hyderabad|
|          6| Customer_6|     Pune|
|          7| Customer_7|Ahmedabad|
|          8| Customer_8|     Pune|
|          9| Customer_9|   Mumbai|
|         10|Customer_10|     Pune|
|         11|Customer_11|    Delhi|
|         12|Customer_12|  Chennai|
|         13|Customer_13|  Chennai|
|         14|Customer_14|Hyderabad|
|         15|Customer_15|   Mumbai|
|         16|Customer_16|  Chennai|
|         17|Customer_17|Hyderabad|
|         18|Customer_18|     Pune|
|         19|Customer_19|  Kolkata|
+-----------+-----------+---------+
only showing top 20 rows

In [1]:
 spark.stop()