In [1]:
from pyspark.sql import SparkSession
spark=SparkSession.builder \
.appName('spark SQL creating dataframe') \
.enableHiveSupport() \
.getOrCreate()

25/04/16 15:14:25 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [2]:
data=[
    (1,"Alice","Mumbai","2023-03-15",True),
    (2,"Bob","Calcutta","2024-05-19",False),
    (3,"Charlie","Banglore","2024-07-28",True)
]
columns=["customer_id","name","city","registration_date","is_active"]

## Spark Read

In [3]:
df_csv=spark.read.format('csv').option('header','true').load('/data/first_100_customers.csv')
df_csv.show()

+-----------+-----------+---------+-----------+-------+-----------------+---------+
|customer_id|       name|     city|      state|country|registration_date|is_active|
+-----------+-----------+---------+-----------+-------+-----------------+---------+
|          0| Customer_0|     Pune|Maharashtra|  India|       2023-06-29|    False|
|          1| Customer_1|Bangalore| Tamil Nadu|  India|       2023-12-07|     True|
|          2| Customer_2|Hyderabad|    Gujarat|  India|       2023-10-27|     True|
|          3| Customer_3|Bangalore|  Karnataka|  India|       2023-10-17|    False|
|          4| Customer_4|Ahmedabad|  Karnataka|  India|       2023-03-14|    False|
|          5| Customer_5|Hyderabad|  Karnataka|  India|       2023-07-28|    False|
|          6| Customer_6|     Pune|      Delhi|  India|       2023-08-29|    False|
|          7| Customer_7|Ahmedabad|West Bengal|  India|       2023-12-28|     True|
|          8| Customer_8|     Pune|  Karnataka|  India|       2023-06-22|     True|
|          9| Customer_9|   Mumbai|  Telangana|  India|       2023-01-05|     True|
|         10|Customer_10|     Pune|    Gujarat|  India|       2023-08-05|     True|
|         11|Customer_11|    Delhi|West Bengal|  India|       2023-08-02|    False|
|         12|Customer_12|  Chennai|    Gujarat|  India|       2023-11-21|    False|
|         13|Customer_13|  Chennai|  Karnataka|  India|       2023-11-06|     True|
|         14|Customer_14|Hyderabad| Tamil Nadu|  India|       2023-02-07|    False|
|         15|Customer_15|   Mumbai|    Gujarat|  India|       2023-03-02|     True|
|         16|Customer_16|  Chennai|  Karnataka|  India|       2023-04-05|    False|
|         17|Customer_17|Hyderabad|West Bengal|  India|       2023-08-21|    False|
|         18|Customer_18|     Pune|      Delhi|  India|       2023-10-04|     True|
|         19|Customer_19|  Kolkata|    Gujarat|  India|       2023-02-05|     True|
+-----------+-----------+---------+-----------+-------+-----------------+---------+
only showing top 20 rows

## Spark SQL

In [4]:
spark.sql('show tables').show()

ivysettings.xml file not found in HIVE_HOME or HIVE_CONF_DIR,/etc/hive/conf.dist/ivysettings.xml will be used

+---------+--------------------+-----------+
|namespace|           tableName|isTemporary|
+---------+--------------------+-----------+
|  default|external_customers_2|      false|
+---------+--------------------+-----------+

In [5]:
df_sql=spark.sql('select * from external_customers_2 where is_active =True').show()

+-----------+---------------+---------+-----------+-------+-----------------+---------+
|customer_id|           name|     city|      state|country|registration_date|is_active|
+-----------+---------------+---------+-----------+-------+-----------------+---------+
|     169004|Customer_169004|   Mumbai|West Bengal|  India|       2023-03-02|     true|
|     169005|Customer_169005|Bangalore|  Telangana|  India|       2023-01-16|     true|
|     169009|Customer_169009|Bangalore|West Bengal|  India|       2023-07-14|     true|
|     169012|Customer_169012|Hyderabad|      Delhi|  India|       2023-11-24|     true|
|     169013|Customer_169013|  Kolkata|      Delhi|  India|       2023-05-22|     true|
|     169015|Customer_169015|     Pune|  Karnataka|  India|       2023-10-14|     true|
|     169016|Customer_169016|  Kolkata|West Bengal|  India|       2023-08-17|     true|
|     169018|Customer_169018|   Mumbai| Tamil Nadu|  India|       2023-08-15|     true|
|     169019|Customer_169019|Hyderabad|Maharashtra|  India|       2023-05-31|     true|
|     169020|Customer_169020|    Delhi|  Karnataka|  India|       2023-07-03|     true|
|     169022|Customer_169022|Ahmedabad|      Delhi|  India|       2023-10-22|     true|
|     169024|Customer_169024|Bangalore|  Telangana|  India|       2023-01-17|     true|
|     169025|Customer_169025|    Delhi|West Bengal|  India|       2023-05-04|     true|
|     169026|Customer_169026|  Kolkata| Tamil Nadu|  India|       2023-01-06|     true|
|     169028|Customer_169028|     Pune|      Delhi|  India|       2023-07-12|     true|
|     169030|Customer_169030|Hyderabad|    Gujarat|  India|       2023-04-07|     true|
|     169034|Customer_169034|     Pune|      Delhi|  India|       2023-03-29|     true|
|     169038|Customer_169038|  Chennai|    Gujarat|  India|       2023-04-06|     true|
|     169042|Customer_169042|Hyderabad|Maharashtra|  India|       2023-06-10|     true|
|     169043|Customer_169043|Ahmedabad|West Bengal|  India|       2023-06-12|     true|
+-----------+---------------+---------+-----------+-------+-----------------+---------+
only showing top 20 rows

## Spark Table

In [6]:
df_table=spark.table('external_customers_2').show()

+-----------+---------------+---------+-----------+----------+-----------------+---------+
|customer_id|           name|     city|      state|   country|registration_date|is_active|
+-----------+---------------+---------+-----------+----------+-----------------+---------+
|       NULL|        Kolkata|Telangana|      India|2023-07-11|             True|     NULL|
|     169004|Customer_169004|   Mumbai|West Bengal|     India|       2023-03-02|     true|
|     169005|Customer_169005|Bangalore|  Telangana|     India|       2023-01-16|     true|
|     169006|Customer_169006|    Delhi| Tamil Nadu|     India|       2023-11-30|    false|
|     169007|Customer_169007|    Delhi|West Bengal|     India|       2023-01-29|    false|
|     169008|Customer_169008|Bangalore|  Telangana|     India|       2023-09-19|    false|
|     169009|Customer_169009|Bangalore|West Bengal|     India|       2023-07-14|     true|
|     169010|Customer_169010|     Pune|  Karnataka|     India|       2023-06-06|    false|
|     169011|Customer_169011|  Kolkata|Maharashtra|     India|       2023-05-06|    false|
|     169012|Customer_169012|Hyderabad|      Delhi|     India|       2023-11-24|     true|
|     169013|Customer_169013|  Kolkata|      Delhi|     India|       2023-05-22|     true|
|     169014|Customer_169014|  Kolkata|  Karnataka|     India|       2023-04-01|    false|
|     169015|Customer_169015|     Pune|  Karnataka|     India|       2023-10-14|     true|
|     169016|Customer_169016|  Kolkata|West Bengal|     India|       2023-08-17|     true|
|     169017|Customer_169017|    Delhi| Tamil Nadu|     India|       2023-08-07|    false|
|     169018|Customer_169018|   Mumbai| Tamil Nadu|     India|       2023-08-15|     true|
|     169019|Customer_169019|Hyderabad|Maharashtra|     India|       2023-05-31|     true|
|     169020|Customer_169020|    Delhi|  Karnataka|     India|       2023-07-03|     true|
|     169021|Customer_169021|  Kolkata|  Karnataka|     India|       2023-12-11|    false|
|     169022|Customer_169022|Ahmedabad|      Delhi|     India|       2023-10-22|     true|
+-----------+---------------+---------+-----------+----------+-----------------+---------+
only showing top 20 rows

## Spark .range
-- want to create dataframe for testing purposes

In [8]:
df_range=spark.range(0,10).show()

+---+
| id|
+---+
|  0|
|  1|
|  2|
|  3|
|  4|
|  5|
|  6|
|  7|
|  8|
|  9|
+---+

In [9]:
data=[
    (1,"Alice","Mumbai","2023-03-15",True),
    (2,"Bob","Calcutta","2024-05-19",False),
    (3,"Charlie","Banglore","2024-07-28",True)
]
columns=["customer_id","name","city","registration_date","is_active"]
df_list=spark.createDataFrame(data,columns)
df_list.show()

+-----------+-------+--------+-----------------+---------+
|customer_id|   name|    city|registration_date|is_active|
+-----------+-------+--------+-----------------+---------+
|          1|  Alice|  Mumbai|       2023-03-15|     true|
|          2|    Bob|Calcutta|       2024-05-19|    false|
|          3|Charlie|Banglore|       2024-07-28|     true|
+-----------+-------+--------+-----------------+---------+

## RDD----->DF

In [11]:
rdd=spark.sparkContext.parallelize([(1,'Aice'),(2,'Bob')])

In [12]:
rdd.take(2)

[(1, 'Aice'), (2, 'Bob')]

In [14]:
df_rdd=rdd.toDF(["customer_id","name"]).show()

+-----------+----+
|customer_id|name|
+-----------+----+
|          1|Aice|
|          2| Bob|
+-----------+----+

In [ ]:
## we can also impose schema by .Schema